project/apps/website/urls.py
# coding:utf-8
from django.urls import path
from django.contrib.auth import views as auth_views
from website import views

app_name = 'website'

urlpatterns = [
    path('', views.HomeView.as_view(), {'share': '1'}, name='home'),
    path('form/', views.FormCaseView.as_view(),  name='form'),
    path('thanks/', views.ThanksView.as_view(),  name='thanks'),
    path('dashboard/login/', views.LoginView.as_view(), name='login'),
    path('dashboard/preliminary/participant/', views.PreliminaryParticipantView.as_view(),
         name='preliminary_participant'),
    path('dashboard/preliminary/participant/<int:pk>/detail/', views.PreliminaryParticipantDetailView.as_view(),
         name='preliminary_participantdetail'),
    path('dashboard/final/participant/', views.FinalParticipantView.as_view(),
         name='final_participant'),
    path('dashboard/final/participant/<int:pk>/detail/', views.FinalParticipantDetailView.as_view(),
         name='final_participantdetail'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('dashboard/reset/password/', views.ResetPasswordView.as_view(), name='reset_password')
]

project/settings/urls.py
#!encoding:utf-8

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Administración de Premio Igualitario'
admin.site.site_title = 'Sitio de Administración Premio Igualitario'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/business/', include('business.urls', namespace="business")),
    path('', include('website.urls', namespace="website")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/business/models.py
#!encoding:utf-8
from django.db import models
from django.contrib.auth.models import User
from common.validators import phone_validator, name_validator, numeric_validator, alphanumeric_validator
from django.db.models import signals
from django.db.models import Sum


class CompanyType(models.Model):

    name = models.CharField(
        verbose_name=u'Nombre',
        max_length=200,
        blank=False,
    )

    created_at = models.DateTimeField(
        verbose_name=u'Fecha de Creación',
        auto_now_add=True
    )

    def __str__(self):
        return u'{0}'.format(self.name)

    class Meta:
        verbose_name = u'Tipo de Empresa'
        verbose_name_plural = u'Tipo de Empresa'
        ordering = ('id',)


class CompanyCategory(models.Model):

    name = models.CharField(
        verbose_name=u'Nombre',
        max_length=200,
        blank=False,
    )

    companytype = models.ForeignKey(
        CompanyType,
        verbose_name=u'Tipo de Empresa',
        on_delete=models.PROTECT
    )

    created_at = models.DateTimeField(
        verbose_name=u'Fecha de Creación',
        auto_now_add=True
    )

    companyquestions = models.CharField(
        verbose_name=u'Lista de Preguntas',
        max_length = 200,
        blank = False,
    )

    minimum_score = models.DecimalField(
        verbose_name=u'Puntaje Minimo',
        default=0,
        max_digits=10,
        decimal_places=2
    )

    def __str__(self):
        return u'{0}'.format(self.name)

    class Meta:
        verbose_name = u'Categoría de Empresa'
        verbose_name_plural = u'Categoría de Empresa'
        ordering = ('id',)


class CompanyQuestion(models.Model):

    name = models.CharField(
        verbose_name=u'Pregunta',
        max_length=200,
        blank=False,
    )

    companycategory = models.ForeignKey(
        CompanyCategory,
        verbose_name=u'Categoría de Empresa',
        on_delete=models.PROTECT
    )

    created_at = models.DateTimeField(
        verbose_name=u'Fecha de Creación',
        auto_now_add=True
    )

    def __str__(self):
        return u'{0}'.format(self.name)

    class Meta:
        verbose_name = u'Preguntas por Categoría'
        verbose_name_plural = u'Preguntas por Categoría'
        ordering = ('id',)


class CompanyCategoryCriteria(models.Model):

    companycategory = models.ForeignKey(
        CompanyCategory,
        verbose_name=u'Categoría de Empresa',
        on_delete=models.PROTECT
    )

    title = models.CharField(
        verbose_name=u'Título',
        max_length=200,
        blank=False,
    )

    name_input = models.CharField(
        verbose_name=u'Nombre del Campo',
        max_length=200,
        blank=False,
    )

    def __str__(self):
        return u'{0}'.format(self.title)

    class Meta:
        verbose_name = u'Criterio de Evaluación por Categoría'
        verbose_name_plural = u'Criterio de Evaluación por Categoría'
        ordering = ('id',)


class Company(models.Model):

    POSTULANT = 'POSTULANT'
    SUITABLE = 'SUITABLE'
    QUALIFIED = 'QUALIFIED'
    FINALIST = 'FINALIST'
    QUALIFIED_FINALIST = 'QUALIFIED_FINALIST'
    WINNER = 'WINNER'
    REJECTED = 'REJECTED'

    STATE_CHOICES = (
        (POSTULANT, u'Postulante'),
        (SUITABLE, u'Por calificar'),
        (QUALIFIED, u'Calificado'),
        (FINALIST, u'Finalista'),
        (QUALIFIED_FINALIST, u'Finalista calificado'),
        (WINNER, u'Ganador'),
        (REJECTED, u'Rechazado'),
    )

    INCOMPLETE = 'INCOMPLETE'
    COMPLETE = 'COMPLETE'

    DATA_STATE_CHOICES = (
        (INCOMPLETE, u'Incompleto'),
        (COMPLETE, u'Completo'),
    )

    name = models.CharField(
        verbose_name=u'Empresa',
        validators=[alphanumeric_validator],
        max_length=120,
        blank=False
    )

    ruc = models.CharField(
        verbose_name=u'Ruc',
        validators=[numeric_validator],
        max_length=11,
        blank=False
    )

    companytype = models.ForeignKey(
        CompanyType,
        verbose_name=u'Tipo de Empresa',
        on_delete=models.PROTECT
    )

    representative = models.CharField(
        verbose_name=u'Representante',
        validators=[name_validator],
        max_length=120,
        blank=False
    )

    email = models.EmailField(
        verbose_name=u'Correo electrónico',
        max_length=120,
        blank=False,
    )

    phone = models.CharField(
        verbose_name=u'Teléfono',
        validators=[phone_validator],
        max_length=9,
        blank=False,
    )

    terms = models.BooleanField(
        verbose_name=u'Términos y Condiciones y Políticas de Privacidad',
        default=False
    )

    companycategories = models.ManyToManyField(
        CompanyCategory,
        verbose_name=u'Categoría'
    )

    videourl = models.URLField(
        verbose_name=u'URL con el video del caso',
        max_length=255,
        blank=True,
    )

    videourl_additional = models.URLField(
        verbose_name=u'URL con el video del caso',
        max_length=255,
        blank=True,
    )

    pdf = models.FileField(
        verbose_name=u'PDF con información del caso',
        max_length=255,
        blank=True,
        upload_to='pdf/'
    )

    pdf_additional = models.FileField(
        verbose_name=u'PDF con información del caso',
        max_length=255,
        blank=True,
        upload_to='pdf/'
    )

    photo = models.FileField(
        verbose_name=u'Evidencia en foto de la iniciativa',
        max_length=255,
        blank=True,
        upload_to='foto/'
    )

    photo_additional = models.FileField(
        verbose_name=u'Evidencia en foto de la iniciativa',
        max_length=255,
        blank=True,
        upload_to='foto/'
    )

    initiative = models.TextField(
        verbose_name=u'Nombre de la iniciativa',
        max_length=255,
        blank=True,
    )

    state = models.CharField(
        verbose_name=u'Estado',
        max_length=20,
        choices=STATE_CHOICES,
        default=POSTULANT
    )

    created_at = models.DateTimeField(
        verbose_name=u'Fecha de Creación',
        auto_now_add=True
    )

    score_preliminary = models.DecimalField(
        verbose_name=u'Puntaje',
        default=0,
        max_digits=10,
        decimal_places=2
    )

    score_final = models.DecimalField(
        verbose_name=u'Puntaje Final',
        default=0,
        max_digits=10,
        decimal_places=2
    )

    data_state = models.CharField(
        verbose_name=u'Estado Formulario',
        max_length=20,
        choices=DATA_STATE_CHOICES,
        default=INCOMPLETE
    )

    def __str__(self):
        return u'{0}'.format(self.name)

    class Meta:
        verbose_name = u'Empresa'
        verbose_name_plural = u'Empresas'
        ordering = ('id',)
        permissions = (
            ('company_preliminary_jury_get', u'Can access preliminary jury dashboard'),
            ('company_final_jury_get', u'Can access final jury dashboard'),
        )


class CompanyDetail(models.Model):

    company = models.ForeignKey(
        Company,
        verbose_name=u'Compañia',
        on_delete=models.CASCADE,
        related_name='questions'
    )

    question = models.ForeignKey(
        CompanyQuestion,
        verbose_name=u'Pregunta',
        on_delete=models.PROTECT
    )

    response = models.TextField(
        verbose_name=u'Respuesta',
        max_length=700,
        blank=True,
    )

    def __str__(self):
        return u''.format("#", self.id)

    class Meta:
        verbose_name = u'Pregunta según la Categoría'
        verbose_name_plural = u'Preguntas según la Categoría'
        ordering = ('id',)


class CompanyDetailEvaluation(models.Model):

    MAX_EVALUATION_PRELIMINARY = 3
    MAX_EVALUATION_FINAL = 5
    PERMISSION_PRELIMINARY = 'business.company_preliminary_jury_get'
    PERMISSION_FINAL = 'business.company_final_jury_get'

    PRELIMINARY = 'PRELIMINARY'
    FINAL = 'FINAL'

    TYPE_CHOICES = (
        (PRELIMINARY, u'Preliminar'),
        (FINAL, u'Final'),
    )

    company = models.ForeignKey(
        Company,
        verbose_name=u'Compañia',
        on_delete=models.CASCADE
    )

    jury = models.ForeignKey(
        User,
        verbose_name=u'Nombre',
        on_delete=models.CASCADE
    )

    comment = models.CharField(
        verbose_name=u'Comentario',
        max_length=250,
        blank=False
    )

    score = models.DecimalField(
        verbose_name=u'Puntaje',
        default=0,
        max_digits=10,
        decimal_places=2
    )

    type = models.CharField(
        verbose_name=u'Tipo',
        max_length=20,
        choices=TYPE_CHOICES,
        default=PRELIMINARY
    )

    created_at = models.DateTimeField(
        verbose_name=u'Fecha de Creación',
        auto_now_add=True
    )

    impact = models.DecimalField(
        verbose_name=u'Impacto',
        default=0,
        max_digits=10,
        decimal_places=2
    )

    creativity = models.DecimalField(
        verbose_name=u'Creatividad',
        default=0,
        max_digits=10,
        decimal_places=2
    )

    social_change = models.DecimalField(
        verbose_name=u'Cambio Social',
        default=0,
        max_digits=10,
        decimal_places=2
    )

    sustainability = models.DecimalField(
        verbose_name=u'Sostenibilidad',
        default=0,
        max_digits=10,
        decimal_places=2
    )

    originality = models.DecimalField(
        verbose_name=u'Originalidad',
        default=0,
        max_digits=10,
        decimal_places=2
    )

    scope = models.DecimalField(
        verbose_name=u'Alcance',
        default=0,
        max_digits=10,
        decimal_places=2
    )

    def save(self, *args, **kwargs):
        self.score = self.impact + self.creativity + self.social_change + self.sustainability + self.originality + \
                     self.scope
        super(CompanyDetailEvaluation, self).save(*args, **kwargs)

    def __str__(self):

project/templates/mailing.html
{% load static %}
<html>
    <head>
        <title>Premio Igualitario</title>
    </head>
    <body bgcolor="#ffffff">
        <table width="100%" align="center" cellspacing="0" cellpadding="0">
            <tr>
                <td align="center" valign="top">
                    <table width="600" align="center" cellspacing="0" cellpadding="0">
                        <tr>
                            <td align="center" valign="top" style="font-family: Arial, Helvetica, sans-serif; font-size: 24px; color: #000000; text-align: left; font-weight: bold; padding-top: 35px; padding-left: 50px; padding-right: 50px; padding-bottom: 35px;">
                                Gracias a tu participaci&oacute;n construimos un Per&uacute; con m&aacute;s igualdad, sin barreras y con un mejor futuro.
                            </td>
                        </tr>
                        <tr>
                            <td align="center" valign="top">
                                <img src="{{ BASE_URL }}{% static 'images/mailing_banner.jpg' %}" width="100%" alt="Premio Igualitario Scotiabank" border="0" style="vertical-align: top;">
                            </td>
                        </tr>
                        <tr>
                            <td align="center" valign="top" style="text-align: center; padding-top: 50px; padding-bottom: 50px; padding-left: 38px; padding-right: 38px;">
                                <a href="mailto:contacto@premioigualitario.com" target="_blank" style="outline: none;"><img src="{{ BASE_URL }}{% static 'images/mailing_box.jpg' %}" width="502" border="0" style="vertical-align: top;"></a>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </body>
</html>

project/templates/mailing_resetpassword.html
{% load static %}
<html>
    <head>
        <title>Premio Igualitario</title>
    </head>
    <body bgcolor="#ffffff">
       <p>Estimado {{ name }}</p>
       <p>La contraseña para tu cuenta en el Dashboard Premio Igualitario, se ha cambiado recientemente.</p>
       <p>Tu nueva contraseña es: {{ password }} </p>
    </body>
</html>

project/templates/participant.html
{% load static %}<!DOCTYPE html>
<html lang="es-PE">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title>{{ TITLE }}</title>
    <meta name="description" content="{{ DESCRIPTION }}">
    <meta name="keywords" content="{{ KEYWORDS }}">
    <meta name="author" content="{{ AUTHOR }}">
    <!-- meta(http-equiv="Cache-control", content="public")-->
    <!-- meta(http-equiv="Expires", content="Tue, 31 Dec 2030 23:59:59 GMT")-->
    <!-- Theme color (Only Chrome Mobile)-->
    <meta name="theme-color" content="#d93649">
    <meta name="msapplication-TileColor" content="#d93649">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="#d93649">
    <!-- Facebook meta tags-->
    <meta property="og:title" content="{{ TITLE }}">
    <meta property="og:description" content="{{ DESCRIPTION }}">
    <meta property="og:type" content="website">
    <meta property="og:url" content="{{ BASE_URL }}">
    <meta property="og:image" content="{{ BASE_URL }}{% static 'images/bg_facebook_share.jpg' %}">
    <meta property="og:locale" content="es_LA">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <!-- Twitter meta tags-->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{{ TITLE }}">
    <meta name="twitter:description" content="{{ DESCRIPTION }}">
    <meta name="twitter:image" content="{{ BASE_URL }}{% static 'images/bg_facebook_share.jpg' %}">
    <meta name="twitter:image:width" content="1200">
    <meta name="twitter:image:height" content="630">
    <link rel="canonical" href="{{ BASE_URL }}">
    <script type="application/ld+json">
      {
        "@context": "http://www.schema.org",
        "@type":    "WebSite",
        "name":     "{{ SHARE_TITLE }}",
        "alternateName": "{{ ALTERNATE_TITLE }}",
        "url":      "{{ BASE_URL }}"
      }
      
    </script>
    <script>
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','GTM-5JX7QD9');
      
    </script>
    <!--Favicon-->
    <link rel="shortcut icon" type="image/png" href="{{ BASE_URL }}{% static 'images/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}?v={{ random }}"><!--[if lte IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body class="loader" data-controller="participant" data-mobile="{% if request.is_mobile %}true{% else %}false{% endif %}" data-url="{{ BASE_URL }}">
    <!-- Google Tag Manager (noscript)-->
    <noscript>
      <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5JX7QD9" height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript)-->
    <div id="loader">
      <div class="loader-inner">
        <div class="box">
          <div class="lds-circle">
            <div>
              <!-- ?xml version="1.0" encoding="utf-8"?-->
              <!-- Generator: Adobe Illustrator 23.1.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)-->
              <svg id="Capa_1" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 215.63 316.67" style="enable-background:new 0 0 215.63 316.67;" xml:space="preserve">
                <style type="text/css">
                  .st0 {
                      fill: #D7D8D8;
                  }
                  
                  .st1 {
                      fill: #FFFFFF;
                  }
                  
                  .st2 {
                      fill: #C10012;
                  }
                  
                  .st3 {
                      fill: #FFF;
                  }
                </style>
                <g>
                  <g>
                    <path class="st3" d="M124.39,214.04c51.67-7.94,91.36-52.69,91.36-106.55c0-59.45-48.36-107.81-107.8-107.81                              C48.51-0.32,0.14,48.04,0.14,107.49c0,55.58,42.29,101.47,96.38,107.2c0.52,0.06,2.22,0.11,2.75,0.15v32.18H66.88v18.8h32.38                              v50.76h22.3v-50.75h32.9v-18.81h-32.9v-32.67C121.94,214.3,124.01,214.1,124.39,214.04z M107.95,196.4                              c-49.03,0-88.92-39.89-88.92-88.91c0-49.03,39.89-88.91,88.92-88.91c49.03,0,88.92,39.89,88.92,88.91                              C196.87,156.52,156.97,196.4,107.95,196.4z"></path>
                  </g>
                  <g>
                    <g>
                      <rect class="st2" x="55.6" y="119.28" width="104.7" height="18.91"></rect>
                    </g>
                    <g>
                      <polyline class="st2" points="119.3,80.8 160.3,80.8 160.3,99.71 55.6,99.71 55.6,80.8 119.3,80.8 			"></polyline>
                    </g>
                  </g>
                </g>
              </svg>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="participant">
      <header id="headerdashboard">
        <div class="headerdashboard-container">
          <div class="headerdashboard-inner">
            <div class="hamburger hamburger--ghost">
              <label><span></span><span></span><span></span></label>
            </div><a href="{% url 'website:home' %}"><img class="logo" src="{% static 'images/logo_banner.png' %}" alt="logo"></a>
            <div class="hamburger js_hamburger">
              <label><span></span><span></span><span></span></label>
              <div class="menu js_menu">
                <p class="user">{{ user.get_full_name }}</p><a class="logout" href="{% url 'website:logout' %}">Cerrar Sesión</a>
              </div>
            </div>
          </div>
        </div>
      </header>
      <section class="section section-index">
        <div class="section-container">
          <div class="section-inner">
            <div class="box">
              <div class="box__item">
                <div class="menu">
                  <div class="title">
                    <p class="text">Postulaciones</p>
                  </div>
                  <div class="subtitle">
                    <p class="text">Filtrar</p>
                  </div>
                  <div class="filter">
                    <p class="text text--title">Calificación</p><a class="option option--active js_filter_state" href="?" data-state=""><span class="circle"></span>
                      <p class="text">Todos</p></a><a class="option js_filter_state" href="?state=QUALIFIED" data-state="QUALIFIED"><span class="circle"></span>
                      <p class="text">Calificados</p></a><a class="option js_filter_state" href="?state=SUITABLE" data-state="SUITABLE"><span class="circle"></span>
                      <p class="text">No calificados</p></a>
                    <div class="artifice">
                      <select class="select js_select_state" name="companystate" id="companystate">
                        <option value="" data-href="">Todos</option>
                        <option value="QUALIFIED" data-href="?state=QUALIFIED">Calificados</option>
                        <option value="SUITABLE" data-href="?state=SUITABLE">No calificados</option>
                      </select>
                    </div>
                  </div>
                  <div class="filter">
                    <p class="text text--title">Categorías</p><a class="option option--active js_filter_category" href="?" data-category=""><span class="circle"></span>
                      <p class="text">Todos</p></a><a class="option js_filter_category" href="?category=1" data-category="1"><span class="circle"></span>
                      <p class="text">Excelencia Igualitaria Grandes Empresas</p></a><a class="option js_filter_category" href="?category=2" data-category="2"><span class="circle"></span>
                      <p class="text">Caso de Éxito Comunicación Interna Grandes Empresas</p></a><a class="option js_filter_category" href="?category=3" data-category="3"><span class="circle"></span>
                      <p class="text">Excelencia Igualitaria PYMES</p></a><a class="option js_filter_category" href="?category=4" data-category="4"><span class="circle"></span>
                      <p class="text">Caso de Éxito Comunicación Interna PYMES</p></a><a class="option js_filter_category" href="?category=5" data-category="5"><span class="circle"></span>
                      <p class="text">Excelencia Igualitaria Emprendimiento</p></a>
                    <div class="artifice">
                      <select class="select js_select_category" name="companycategory" id="companycategory">
                        <option value="" data-href="">Todos</option>
                        <option value="1" data-href="?category=1">Excelencia Igualitaria Grandes Empresas</option>
                        <option value="2" data-href="?category=2">Caso de Éxito Comunicación Interna Grandes Empresas</option>
                        <option value="3" data-href="?category=3">Excelencia Igualitaria PYMES</option>
                        <option value="4" data-href="?category=4">Caso de Éxito Comunicación Interna PYMES</option>
                        <option value="5" data-href="?category=5">Excelencia Igualitaria Emprendimiento</option>
                      </select>
                    </div>
                  </div>
                </div>
              </div>
              <div class="box__item">
                <div class="participant">{% for participant in object_list %}<a class="participant__item" href="{% url 'website:preliminary_participantdetail' participant.id %}">
                    <div class="row row--top"><span class="tag">{{ participant.companycategories.first }}</span>{% if participant.state == 'QUALIFIED' or participant.state == 'FINALIST' or participant.state == 'WINNER'%}
                      <div class="state"><span class="state__text">{{ participant.get_state_display }}</span><span class="state__icon state__icon--success"></span></div>{% else %}
                      {{ participant.companydetailevaluation_set.jury }}
                      {% if participant.companydetailevaluation_set.all|length > 0 %}
                      {% for evaluation in participant.companydetailevaluation_set.all %}
                      {% if evaluation.jury.username == user.get_username %}
                      {% else %}
                      <div class="state"><span class="state__text">Por calificar</span><span class="state__icon state__icon--alert"></span></div>{% endif %}
                      {% endfor %}
                      {% for evaluation in participant.companydetailevaluation_set.all %}
                      {% if evaluation.jury.username == user.get_username %}
                      <div class="state"><span class="state__text">Calificado</span><span class="state__icon state__icon--success"></span></div>{% endif %}
                      {% endfor %}
                      {% else %}
                      <div class="state"><span class="state__text">{{ participant.get_state_display }}</span><span class="state__icon state__icon--alert"></span></div>{% endif %}
                      {% endif %}
                    </div>
                    <div class="row row--medium"><span class="name">{{ participant.initiative }}</span></div>
                    <div class="row row--bottom"><span class="company">{{ participant.name }}</span>
                      <!--|{# {% if participant.state == 'QUALIFIED' or participant.state == 'FINALIST'%}-->
                      <!--span.point {{ participant.score_preliminary|floatformat:"-2" }} ptos.-->
                      <!--|{% endif %} #}-->{% for evaluation in participant.companydetailevaluation_set.all %}
                      {% if evaluation.jury.username == user.get_username and evaluation.type == 'PRELIMINARY' %}<span class="point">{{ evaluation.score|floatformat:"-2" }} ptos.</span>{% endif %}
                      {% endfor %}
                    </div></a>{% endfor %}</div>{% if is_paginated %}
                <div class="paginator" role="navigation" aria-label="Pagination">{% if page_obj.has_previous %}<a class="arrow arrow--prev" href="?page={{ page_obj.previous_page_number }}{% for key,value in request.GET.items %}{% ifnotequal key 'page' %}&amp;{{ key }}={{ value }}{% endifnotequal %}{% endfor %}"></a>{% endif %}
                  <div class="number"><span class="number text">{{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span></div>{% if page_obj.has_next %}<a class="arrow arrow--next" href="?page={{ page_obj.next_page_number }}{% for key,value in request.GET.items %}{% ifnotequal key 'page' %}&amp;{{ key }}={{ value }}{% endifnotequal %}{% endfor %}"></a>{% endif %}
                </div>{% endif %}
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    <script src="{% static 'js/vendor/vendor_all.js' %}?v={{ random }}" type="text/javascript"></script>
    <script src="{% static 'js/bundle.js' %}?v={{ random }}" type="text/javascript"></script>
  </body>
</html>